### PR TITLE
[turborepo] Add missing dependency on tsup

### PR DESCRIPTION
**Pull request by yonas**

### CODE REVIEW

**Review by mehulkar — CHANGES_REQUESTED** [review]
We definitely don't want to merge this without the lockfile update, but can you say where the dep also? I haven't run into a situation yet where I needed tsup and didn't have it.

**Comment by yonas** [comment]
@mehulkar tsup is needed during the build: `pnpm -- turbo run build --filter=docs`

**Comment by mehulkar** [comment]
Can you share your output if you're running into an issue? I'm able to build docs with that command in `main`.

**Comment by yonas** [comment]
I removed tsup from packages.json and node_modules, but I don't get the error anymore.

I'll reopen this if I'm able to reproduce.

**Pull request closed without merging**
