### PR TITLE
Fixed prisma example to allow importing interfaces from database

### PR DESCRIPTION
**Pull request by mattpocock**
For context:

https://twitter.com/javier_dev/status/1592532624635199489

### CODE REVIEW

**Comment by javiercr** [comment]
That was fast 😳

Also worth mentioning that right now the [Using Prisma with Turborepo](https://turbo.build/repo/docs/handbook/prisma) guide is recommending having `database` package that directly export `./index.ts`:

```json
{
  "main": "./index.ts",
  "types": "./index.ts"
}
```

While this example stills uses a `tsup` build step and uses `./dist/index.mjs` for `main` and `/.dist/index.d.ts` for `types.
https://github.com/vercel/turbo/blob/main/examples/with-prisma/packages/database/package.json

**Review by mehulkar — APPROVED** [review]

**Comment by dallenbaldwin** [comment]
I'm stumbling upon this tonight while trying to get a start script to work for my server code (express backend)

I followed the guide in the docs, setting the `main` and `types` properties in my database package to `./index.ts` 

During development, everything is peachy, but the moment I need to just run the server in production mode, i get this

```
> server@1.0.0 start
> node dist/index.js

/home/.../packages/database/index.ts:1
export * from '@prisma/client';
^^^^^^

SyntaxError: Unexpected token 'export'
```

I went the `tsup` path and got the start script to work, but am also confused as to which is the "correct" way

**Comment by dallenbaldwin** [comment]
Is there any update on this? 

I cannot get the latest version of Prisma to work in production if I follow the guide on the site and can't get it to work in development if I follow the `with-prisma` example in the examples. 

Has anyone been able to get Prisma to work?

**Comment by dallenbaldwin** [comment]
I believe I might have found a solution that might be worth a try for those using a plain express backend. 

Thanks to this [article](https://www.infoq.com/articles/nodejs-monorepo/) in the Fix module resolution for development and production section, I was able to make use of Node's conditional exports to resolve everything correctly for both dev and prod, while using as minimal a setup as the site's guide proposes.

If any of this could be done better, I'm all ears. I'm  _very much_ a novice with turborepo and monorepos in general.

packages/database/package.json

```json
{
  "name": "database",
  "main": "./src/index.ts",
  "types": "./src/index.ts",
  "exports": {
    ".": {
      "prod": "./dist/index.js",
      "default": "./src/index.ts"
    }
  },
  "scripts": {
    "build": "tsc",
    ...
  }
  ...
}
```

packages/database/src/index.ts

```typescript
export * from '@prisma/client';
```

apps/server/package.json

```json
{
  ...
  "scripts": {
    "start": "node --conditions=prod dist/index.js",
    "build": "tsc",
    "dev": "nodemon src/index.ts"
  },
  ...
}
```

package.json

```json
{
  "name": "root",
  "private": true,
  "workspaces": [
    "packages/*",
    "apps/*"
  ],
  "scripts": {
    "dev": "npm run up & npx turbo dev",
    "build": "npx turbo build",
    "start": "export NODE_ENV=production && npx turbo start",
    "up": "docker-compose up",
    ...
  },
  ...
}
```

turbo.json

```json
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "start": {
      "cache": false,
      "dependsOn": [
        "^db:generate",
        "build"
      ]
    },
    "dev": {
      "dependsOn": [
        "^db:generate"
      ],
      "cache": false
    },
    "build": {
      "dependsOn": [
        "^db:generate",
        "^build"
      ],
      "outputs": [
        "dist/**",
        "build/**",
        "vender/**"
      ]
    },
    "db:generate": {
      "cache": false
    },
    "db:push": {
      "cache": false
    }
  }
}
```

**Pull request merged**
