### PR TITLE
Rename TopologicGraph to WorkspaceGraph

### PR DESCRIPTION
**Pull request by mehulkar**
TopologicGraph in the engine sounds like it's for tasks, since the engine is for executing tasks, but it's really the workspace graph.

### CODE REVIEW

**Comment by NicholasLYang** [comment]
Just to be clear, topological in this context means topologically sorted? Seems like there's other variables in this context using that term and I'm not really sure what it implies. Otherwise LGTM

**Comment by NicholasLYang** [comment]
Hmm yeah maybe this is me overthinking this but topological is a really general word. I'd be in favor of removing it entirely unless we're talking about topological sorting.

**Review by NicholasLYang — APPROVED** [review]

**Review by tknickman — APPROVED** [review]
Can you also rename some of the functions in `context.go` (like `populateTopologicGraphForPackageJSON` for example) - I think that's the last place we refer to TopologicalGraph

**Comment by mehulkar** [comment]
@tknickman great call, updated!

**Pull request merged**
