### PR TITLE
chore: move react, react-dom from devDependency to dependency in several examples

### PR DESCRIPTION
**Pull request by ghdtjgus76**
### Description
I moved the react and react-dom libraries from devDependencies to dependencies in several examples. 
Additionally, in the with-tailwind example, there was a duplicate react dependency listed in both peerDependencies and devDependencies, so I removed it from devDependencies.

That's a very minor question, but in the with-tailwind example, react is specified as a peerDependency. 
How should it be specified in the other examples?

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 59d1ea879c2d0162809d61425531eac2d1cf4408

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by anthonyshew — APPROVED** [review]
Thanks for this!

It doesn't need to be in `peerDependencies` for these simplistic examples. Not sure how it got there. 😄

**Comment by anthonyshew** [comment]
Could you fix the merge conflicts? Sorry about those. Thanks!

**Comment by ghdtjgus76** [comment]
> Could you fix the merge conflicts? Sorry about those. Thanks!

I've resolved the merge conflict!

**Comment by anthonyshew** [comment]
It looks like `with-rollup` is now failing. 🤔

**Comment by ghdtjgus76** [comment]
> It looks like `with-rollup` is now failing. 🤔

I really solved it this time!

**Comment by anthonyshew** [comment]
Great, thanks!

**Pull request merged**
