### PR TITLE
chore: update `update-informer` to 1.1

### PR DESCRIPTION
**Pull request by mgrachev**
### Description

A new version of `update-informer` has been released: [v1.1](https://github.com/mgrachev/update-informer/releases/tag/v1.1.0).

### CODE REVIEW

**Comment by arlyon** [comment]
Nice! thanks for this. I am merging main into here and approving the remaining CI

**Comment by mgrachev** [comment]
The PR was rebased.

**Comment by arlyon** [comment]
I ran taplo to fix the formatting lint and enabled auto-merge

**Comment by mgrachev** [comment]
> I ran taplo to fix the formatting lint and enabled auto-merge

Your approval is needed to run auto-merge

**Review by arlyon — APPROVED** [review]

**Comment by arlyon** [comment]
All done, TY!

**Pull request merged**
