### PR TITLE
Update `swc_core` to `v0.72.4`

### PR DESCRIPTION
**Pull request by kdy1**
### Description

I expected this to make compile much faster, but I found that turbopack is using serde of AST nodes.
I'll investigate

### Testing Instructions

---

 - fix WEB-798 ([link](https://linear.app/vercel/issue/WEB-798))
 - Closes https://github.com/vercel/turbo/issues/4092

### CODE REVIEW

**Review by sokra — CHANGES_REQUESTED** [review]
Also need some changes in next.js https://github.com/vercel/next.js/pull/47589

**Comment by kdy1** [comment]
Drafting as [CI of SWC publish action](https://github.com/swc-project/swc/actions/runs/4551208787) failed

**Comment by kdy1** [comment]
I'll create another PR to update swc_core to newer versions

**Comment by kdy1** [comment]
See https://github.com/vercel/turbo/pull/4470

**Pull request closed without merging**
