### PR TITLE
Improvements on kitchen-sink example

### PR DESCRIPTION
**Pull request by zsh77**
### Description

- improved React imports by using `import React from "react"` instead of `import * as React from "react"`
- moved content of `@repo/jest-presets` package one level up and out of /jest directory for better accessibility. (in order to import the jest presets like `@repo/jest-presets/node` instead of `@repo/jest-presets/jest/node` )
- update the main `README.md` to have updated apps and packages informations

### Testing Instructions

Running `npx create-turbo@latest -e kitchen-sink` and then both `pnpm dev` and `pnpm test` should work fine as they do already.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c9b7e6a0e47da65d7c41067f359674641ff08f4f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by anthonyshew — APPROVED** [review]
Thank you once again!

**Comment by magnusriga** [comment]
@zsh77 Thanks for the update. Quick question: Does this example not add 'use client' to all components coming from repo/ui?

**Comment by zsh77** [comment]
> @zsh77 Thanks for the update. Quick question: Does this example not add 'use client' to all components coming from repo/ui?

@magnusriga yes it adds "use client" to the output index.js and index.mjs files generated in dist directory because of 
```
  banner: {
    js: "'use client'",
  }
```
in `/packages/ui/tsup.config.ts`

**Pull request merged**
