### PR TITLE
docs(storybook): update documentation to the latest versions available for pnpm installation

### PR DESCRIPTION
**Pull request by javiev**
### Description

Starting a project with TurboRepo, Storybook 8+, and Next.js 14 with App Router, I encountered issues using the current guides, which prevented an effective installation. This fork aims to update the documentation to address these issues, providing clear, updated steps for a successful installation of these technologies. Evidence of initial challenges and positive outcomes following the suggested documentation adjustments are included, making the process smoother for future users.

I hope the suggested changes prove useful to the community. I'd like to thank the Vercel development team for providing us with powerful and innovative tools, facilitating the advancement of our projects with cutting-edge technology.

### Testing Instructions

In the project development process, the first issue emerged when using **pnpm dlx sb init --skip-install**, leading to complications. To tackle a second issue regarding dependencies, **"ui": "workspace:*"** was replaced with **"@repo/ui": "workspace:*"**, modifying the declaration approach. For the third issue, importing components was adjusted from **import { Button } from 'ui'** **to import { Button } from '@repo/ui/button'**, solving import problems. These suggested changes showcased an improvement in the final results.

### Using pnpm dlx sb init --skip-install led to the first issue.

SCR-20240413-plba

### Replacing "ui": "workspace:*" with "@repo/ui": "workspace:*" addressed a dependency problem.

**before**

SCR-20240413-posk

**after**

SCR-20240413-ppbd

### Changing imports from import { Button } from 'ui' to import { Button } from '@repo/ui/button' fixed import issues.

**before**

SCR-20240413-ppiz

**after**

SCR-20240413-pppz

### Final Outcome: The implementation of these changes led to a successful setup and integration.

SCR-20240413-psgm

### CODE REVIEW

**Comment by anthonyshew** [comment]
Thanks for this update!

It looks like a merge conflict has come up due to another community PR. Could you fix that up and then I can approve and we can merge?

**Comment by javiev** [comment]
@anthonyshew conflict fixed, please review again!

**Review by anthonyshew — APPROVED** [review]
Great, thank you!

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 6680be74c99694f73aff616996ba1c8e479c0be1

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Pull request merged**
