### PR TITLE
Generate JSON Schema from Golang structs

### PR DESCRIPTION
**Pull request by Schniz**
This PR continues the amazing work done in #634 and #726.

Instead of generating the JSON schema from a separate TypeScript file, this commit introduces a new CLI (to avoid bloating the main one) that will output a JSON schema from the struct definition itself, including the actual code comments.

This will allow to better integration and to avoid differences between the two codebases.

### CODE REVIEW

**Comment by Schniz** [comment]
Oh.

```
cli:schema: CGO_ENABLED=0 go build -o schema-generation.exe "-ldflags=-s -w" -trimpath ./cmd/schema-generation
cli:schema: /bin/sh: go: command not found
cli:schema: make: *** [schema-generation] Error 127
```

Not sure that we want to install golang to make this work.

**Comment by jaredpalmer** [comment]
Let’s ponder hosting of the schema on .org in our 1:1

**Comment by Schniz** [comment]
Add discussed, we should investigate whether we want to make it a build artifact that will be rewritten to in the website 😄

**Comment by jaredpalmer** [comment]
@Schniz what's your suggestion on how to deal with versioning the schema?

**Pull request closed without merging**
