### PR TITLE
fix(ci): require go integration

### PR DESCRIPTION
**Pull request by tknickman**
Introduced when moving go integration tests into our main test workflow:

https://github.com/vercel/turbo/pull/3429

### CODE REVIEW

**Review by chris-olszewski — APPROVED** [review]
Since we're now triggering these from the main we should update the patterns for `go` to include `crates/turborepo*` so we trigger on Rust changes that directly affect our CLI. It looks like right now we just run if `cli/` changes. This does mean we will run Go unit tests when Rust code changes though 😢

**Review by arlyon — APPROVED** [review]
Approved pending CI passing :)

**Review by mehulkar — CHANGES_REQUESTED** [review]
I think we want #3442 instead

**Review by mehulkar — APPROVED** [review]
Never mind, this makes sense now

**Comment by tknickman** [comment]
@chris-olszewski yeaaaa, then we're going to run these no matter what. We really need to break these down by product instead of language

**Pull request merged**
