### PR TITLE
Reduce macro usage in turbo-tasks-testing

### PR DESCRIPTION
**Pull request by bgw**
## What?

Replaces the `turbo_tasks_testing::run!` macro with a `run` function that requires an opaque registration argument generated by the `register!` macro.

## Why?

A few reasons:
- `cargo fmt` doesn't work inside macros (with the exception of function-like macros), so our tests weren't getting autoformatted.
- When a test fails, it was hard to know what line it failed on, because the failure is attributed to the first line of the macro usage.

## Related Changes

- This also changes many (though not all) `.await?`s into `.await.unwrap()`s. The reason for this is similar: it's easier to attribute the line that causes a panic than the line that returns an error. I left some tests alone as there were more `?`s than I felt like changing.

- `register!()` now takes an optional list of other register functions to call. The tests in `turbo-tasks-fetch` use this.

## Testing Instructions

```
cargo nextest run
```

### CODE REVIEW

**Comment by bgw** [comment]
* **#8832** <a href="https://app.graphite.dev/github/pr/vercel/turbo/8832?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bgw and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by arlyon — COMMENTED** [review]
Yay no lazy_static!

**Review by arlyon — COMMENTED** [review]
Also very much _for_ unwraps in tests 👍

**Review by arlyon — APPROVED** [review]
Nice!

**Comment by bgw** [comment]
### Merge activity

* **Jul 25, 2:43 PM EDT**: @bgw merged this pull request with [Graphite](https://app.graphite.dev/github/pr/vercel/turbo/8832).

**Pull request merged**
