### PR TITLE
use stderr for human readable output

### PR DESCRIPTION
**Pull request by ForsakenHarmony**
TODO: read port from stdout for benches

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3547** <a href="https://app.graphite.dev/github/pr/vercel/turbo/3547" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/vercel/turbo/3547?utm_source=stack-comment).

**Review by alexkirsz — APPROVED** [review]
🚢

**Comment by ForsakenHarmony** [comment]
@alexkirsz still need to fix the benchmarks which try to read the port from stdout

**Comment by ForsakenHarmony** [comment]
very outdated

**Pull request closed without merging**
