### PR TITLE
add go linting and examples to single workflow

### PR DESCRIPTION
**Pull request by sokra**

### CODE REVIEW

**Review by mehulkar — COMMENTED** [review]
What's the benefit of a single workflow? I feel like one ~1000 line yaml file is going to be harder to understand/maintain/debug than a bunch of 50-100 line configs

**Review by NicholasLYang — APPROVED** [review]

**Comment by NicholasLYang** [comment]
@mehulkar probably startup time and runner allocation, no? We allocate one runner for longer which lets us avoid startup time. I agree that the file is a bit of a behemoth but it's fairly well organized imo.

**Comment by NicholasLYang** [comment]
It might be worth doing a test run by opening a PR and checking if the workflow runs correctly.

**Comment by sokra** [comment]
> What's the benefit of a single workflow? I feel like one ~1000 line yaml file is going to be harder to understand/maintain/debug than a bunch of 50-100 line configs

* It will allow use to correctly run conditional jobs and reporting a single required PR check.
* All jobs as shows in a single summary, which is much more visible.
* You can pull out jobs into sub-workflows if you like to.
* It also summarizes all CI jobs into a single PR comment to make it easier to see what's the problem (in future we might even pull out jobs details into the PR comment)

> probably startup time and runner allocation, no?

It doesn't change how runners are used. Each job in a workflow has an independent runner

> It might be worth doing a test run by opening a PR and checking if the workflow runs correctly.

The workflow will test itself when changed. For PRs that change the .github/workflows/test.yml file all jobs will run unconditionally even the jobs that usually only run on push (expect for a few steps that we don't want to run on PRs).

**Pull request merged**
