### PR TITLE
Move architecture doc to turbopack

### PR DESCRIPTION
**Pull request by mehulkar**
Not sure if this is what we actually want, but there was some talk about either moving it internal, or adding turborepo material into it.

### CODE REVIEW

**Comment by jaredpalmer** [comment]
We should add a turborepo section

**Comment by jaredpalmer** [comment]
but this can go here for now

**Review by jridgewell — APPROVED** [review]

**Comment by nathanhammond** [comment]
Do we link to this from anywhere?

**Comment by mehulkar** [comment]
> Do we link to this from anywhere?

Only one I know of is @padmaia's tweet here: https://twitter.com/padmaia/status/1585338274687508481, but it's a permalink, so it should be safe

**Pull request merged**
