### PR TITLE
fix(turbopack): Use correct method for the proxy of `fetch`

### PR DESCRIPTION
**Pull request by kdy1**
### Description

We should use [`Proxy::all`](https://docs.rs/reqwest/0.11.26/reqwest/struct.Proxy.html#method.all) instead of `Proxy::http` or `Proxy::https`.

Closes PACK-2448

### Testing Instructions

See next.js counterpart: https://github.com/vercel/next.js/pull/63309

### CODE REVIEW

**Review by kwonoj — APPROVED** [review]
I tried this but it still didn't pass the test in next.js - did you able to make it actually work?

**Comment by kdy1** [comment]
Actually nope, I think it's a bug of `reqwest`.

**Comment by kdy1** [comment]
It works if I add 

```rust
let url = url.replace("https://", "http://");
```

so I think `reqwest` is not sending https requests to the proxy, regardless of the method.

**Comment by kwonoj** [comment]
That's what I saw as well (https://vercel.slack.com/archives/C03EWR7LGEN/p1707871876798169?thread_ts=1707788191.248449&cid=C03EWR7LGEN)

**Comment by kdy1** [comment]
Closing in favor of https://github.com/vercel/turbo/pull/8165

**Pull request closed without merging**
