### PR TITLE
Sync Cargo.lock with Next.js

### PR DESCRIPTION
**Pull request by wbinnssmith**
Updates socket2, tokio, and tokio-macros

### CODE REVIEW

**Comment by chris-olszewski** [comment]
For whatever reason `tokio` being at `1.37.0` breaks our Windows builds at the linking step. [e.g.](https://github.com/vercel/turbo/actions/runs/9292392137/job/25573267715?pr=8246#step:5:28504)

This is something I want to get to the bottom of, but don't have the time to dedicate right now to figuring it out. Is the latest `tokio` version required for Next.js?

**Comment by wbinnssmith** [comment]
> For whatever reason `tokio` being at `1.37.0` breaks our Windows builds at the linking step. [e.g.](https://github.com/vercel/turbo/actions/runs/9292392137/job/25573267715?pr=8246#step:5:28504)
> 
> This is something I want to get to the bottom of, but don't have the time to dedicate right now to figuring it out. Is the latest `tokio` version required for Next.js?

Looks like the reason it was update was to match turbo's, which isn't the case: https://github.com/vercel/next.js/commit/99fff19d974ca4adaae1d6f55878e2b8b296435a

@bgw was this a mistake?

**Comment by bgw** [comment]
> Looks like the reason it was update was to match turbo's, which isn't the case: https://github.com/vercel/next.js/commit/99fff19d974ca4adaae1d6f55878e2b8b296435a
> 
> @bgw was this a mistake?

Turbo *was* on 1.37.0 until yesterday: https://github.com/vercel/turbo/commit/7875ab2f67

**Comment by wbinnssmith** [comment]
Closing in favor of https://github.com/vercel/next.js/pull/66391

**Pull request closed without merging**
