### PR TITLE
add logs command to turbo CLI

### PR DESCRIPTION
**Pull request by chelkyl**
* Adds a 'logs' command providing the ability to review replay logs and hashes of previously-run tasks
* Addresses [dcherman's request](https://github.com/vercel/turborepo/pull/822#issuecomment-1059209652) from #822
* I have been learning golang along the way so any feedback is appreciated!

Replay logs of most recently run tasks sorted by task execution:
image

List all hashes found in cache folder:
image

Replay logs of specific task hashes:
image

Replay last run's logs sorted by task duration from longest to shortest:
image

Replay last run's logs sorted by task start time and showing all metadata:
image
As list:
image

Related to #822 

TODO:

- [x] Add sort by start and end time
  - [x] Start time uses the time value used for calculating duration in run.go
  - [x] End time is calculated on demand from start + duration
  - [x] If --all, default sort to start time instead of alnum
- [x] Refactor --list-format: rename to --include-metadata and allow multiple
  - [x] If --list, output as csv with header. Otherwise, output as info log at end of replay, one line per requested metadata point
- [x] ~~Include remote logs~~ unnecessary because remote logs are fetched during run and it is impractical to fetch all remote logs just for this

### CODE REVIEW

**Comment by weyert** [comment]
I am liking this idea :)

**Comment by gsoltis** [comment]
@chelkyl can you say more about your use case for this command? I think we would like to avoid having hashes leak into the UX to the extent possible, so maybe there is another way to address the particular content you are interesting in replaying?

**Comment by chelkyl** [comment]
@gsoltis This command was to address [dcherman's comment](https://github.com/vercel/turborepo/pull/822#issuecomment-1059209652). The original request was for some way to view the logs that were hidden if you run with `--output-logs=new-only`. Over time, I expanded the scope to add some very minor task history querying capability, restrict output to the hashes you specify, show more data about the tasks, sort the output, and format the output.

I would understand if this isn't a compelling use case!

**Comment by gsoltis** [comment]
I can definitely see the utility in getting the logs for tasks that were run. I think the challenge is going to be in finding a good way to address them. 

I like the idea of tracking recent runs. That could tie in nicely with eventual better management of the cache. I also like the idea of supplying the same arguments to `turbo logs` that were supplied to `turbo run`, along with the particular tasks of interest (`web#build`, `api#test`, etc.) to replay those logs, or an appropriate message on a cache miss.

**Comment by chelkyl** [comment]
Agreed! The hash seemed to be the best solution, especially because the cached log folders are named by their hash.
However, it would be great to support task names (in addition to hashes?), since I could include [task globbing](https://github.com/vercel/turborepo/pull/1088).

How do you think task names support should be implemented? My initial thought is to add another file like the last run log that is just a JSON file mapping task name to hash that is only added to during `turbo run`.

**Comment by gsoltis** [comment]
I think having each `turbo run` produce a manifest would be a good idea, and I think @nathanhammond was interested in something like that as well. Maybe the way to go about this is to start an RFC for what that file should look like, and then the `logs` command would read those to find log files?

**Comment by nathanhammond** [comment]
Heya @chelkyl! @gsoltis is 100% correct about my opinion. I believe that each run should produce a unique identifier that can be used to go back and look up what happened. Conceptually, `turbo run => ID => look up individual task logs and caches`. In my imagination all of the identifiers would be opaque hashes, possibly excepting some (ignored) portion of the identifier for the run that encodes the start time, or a specified name. (Time would only be for monotonic sorting on a single box, not for absolute time. Any name would just be a human-readable prefix/suffix. Both would be ignored by the program.)

**Comment by chelkyl** [comment]
I see! I hadn't even considered uniquely identifying, storing, and isolating each `turbo run` call.
How would the id hash be generated? Would it be a hash on all of the tasks or their hashes for that run?

**Comment by gsoltis** [comment]
@chelkyl If we aren't using it for a cache hit, which I think we wouldn't be, you could use a uuid. A nice-to-have feature would be something easily time-sortable.

**Comment by anthonyshew** [comment]
This one's looking a little stale, folks. Seeing as we're nearly complete with our Rust port, I'm going to close this out as this would shortly end up being deleted code if it were to land.

**Pull request closed without merging**
