### PR TITLE
feat(cli): auto excludes for frameworks

### PR DESCRIPTION
**Pull request by tknickman**
We never need to cache `.next/cache/**`, this PR extends our framework inference to also include globs that can be automatically added to includes and excludes. 

For now this is being used ONLY for the excludes on Next.js, but could be extended in the future. 

NOTE: This can be done now by adding the glob to your outputs:

```json filename=turbo.json
{
  "pipeline": {
    "build": {
      "outputs": [".next/**", "!.next/cache/**"]
    },
    "lint": {
      "outputs": []
    }
  }
}
```

Because we support this now, we may want to solve this via documentation only instead of adding this automatically (too magic-y)

### CODE REVIEW

**Review by mehulkar — COMMENTED** [review]
Isn't `.next/` already git-ignored?

**Comment by tknickman** [comment]
It is, but this is for outputs (what we're caching).

**Comment by mehulkar** [comment]
I'm a bit concerned that we just got rid of magic `outputs` defaults in #2712, and then we're adding it back in 🤔 . Would it make more sense to put this in examples/templates/docs instead of in framework inference?

**Comment by tknickman** [comment]
Yep that's an option, that's why this PR exists (to discuss which we prefer!)

**Comment by tknickman** [comment]
Going the docs route here

**Pull request closed without merging**
