### PR TITLE
Use mimalloc in next-dev

### PR DESCRIPTION
**Pull request by alexkirsz**

### CODE REVIEW

**Review by jridgewell — APPROVED** [review]

**Comment by jaredpalmer** [comment]
are we merging?

**Comment by kwonoj** [comment]
Just got build result from next-swc, good to go.

**Comment by Jerrody** [comment]
@alexkirsz 
What's the reason to use `mimalloc` instead of `mimalloc-rust`?

**Comment by Jerrody** [comment]
> @Jerrody `mimalloc` is the most well-maintained of the two.

How did you understand? Both of them are `1.7.6`. Also, `mimalloc_rust` has an exposed `mimalloc`'s API.

**Comment by Jerrody** [comment]
> @Jerrody `mimalloc` is the most well-maintained of the two.
This is the first thing, the second what's the purpose of creating a `TurboMalloc` why don't just use?
```rs
static ALLOC: mimalloc_rust::GlobalMiMalloc = mimalloc_rust::GlobalMiMalloc;
```
It doesn't give any benefits from creating an addition type. At any rate, when you specify the global allocator all allocations in Rust will be handled from specified global allocator.

**Comment by alexkirsz** [comment]
> This is the first thing, the second is what's the purpose of creating a `TurboMalloc` why don't use this:
> 
> ```rust
> static ALLOC: mimalloc_rust::GlobalMiMalloc = mimalloc_rust::GlobalMiMalloc;
> ```
> 
> It doesn't give any benefits from creating an additional type. At any rate, when you specify the global allocator all allocations in Rust will be handled from the specified global allocator.
> 
> In my opinion, this PR doesn't give any benefit, reason, or sense, but I'm not a maintainer.

You still need to explicitly declare `extern crate` if you mean to use an allocator declared this way in another crate. I find the `#[global_allocator]` declaration clearer. In fact, we made this exact mistake before when depending on `turbo-malloc` and not declaring `extern crate turbo_malloc`. Which means that, at the moment, `next-dev` isn't using `mimalloc` at all.

**Comment by Jerrody** [comment]
> > This is the first thing, the second is what's the purpose of creating a `TurboMalloc` why don't use this:
> > ```rust
> > static ALLOC: mimalloc_rust::GlobalMiMalloc = mimalloc_rust::GlobalMiMalloc;
> > ```
> > 
> > It doesn't give any benefits from creating an additional type. At any rate, when you specify the global allocator all allocations in Rust will be handled from the specified global allocator.
> > In my opinion, this PR doesn't give any benefit, reason, or sense, but I'm not a maintainer.
> 
> You still need to explicitly declare `extern crate` if you mean to use an allocator declared this way in another crate. I find the `#[global_allocator]` declaration clearer. In fact, we made this exact mistake before when depending on `turbo-malloc` and not declaring `extern crate turbo_malloc`. Which means that, at the moment, `next-dev` isn't using `mimalloc` at all.

I still don't understand:
1) Why switch to `mimalloc`?
2) Why need to create an additional type `TurboMalloc`?

But you're right that need to declare a global allocator in bin file.

**Comment by Jerrody** [comment]
> You still need to explicitly declare `extern crate` if you mean to use an allocator declared this way in another crate. I find the `#[global_allocator]` declaration clearer.

About that I didn't say nothing against.

**Review by sokra — APPROVED** [review]
Looks good, but this probably has to find it's way into next-swc on next.js side too @kwonoj

**Comment by alexkirsz** [comment]
I don't see a reference to mimalloc in Next.js so we might be good there.

**Comment by sokra** [comment]
> @alexkirsz next.js use `mimalloc` here https://github.com/vercel/next.js/blob/canary/packages/next-swc/crates/napi/src/lib.rs#L35

Can we use the same method for our code?

**Comment by alexkirsz** [comment]
@sokra This is what we were doing previously for NFT. We can do this here too, I just thought the #[global_allocator] way is cleaner (no implicit behavior).

**Comment by sokra** [comment]
> We can do this here too, I just thought the #[global_allocator] way is cleaner (no implicit behavior).

I'm fine with any of these ways, but I'm all for consistency. It should be the same way in next-swc and in this repo. I don't want to introduce random differences between tested version and published version.

**Comment by Jerrody** [comment]
> > You still need to explicitly declare `extern crate` if you mean to use an allocator declared this way in another crate. I find the `#[global_allocator]` declaration clearer. In fact, we made this exact mistake before when depending on `turbo-malloc` and not declaring `extern crate turbo_malloc`. Which means that, at the moment, `next-dev` isn't using `mimalloc` at all.
> 
> I still don't understand:
> 
> 1. Why switch to `mimalloc`?
> 2. Why need to create an additional type `TurboMalloc`?
> 
> But you're right that need to declare a global allocator in the bin file.
> 
> > You still need to explicitly declare `extern crate` if you mean to use an allocator declared this way in another crate. I find the `#[global_allocator]` declaration clearer.
> 
> About that, I didn't say anything against it. Everything is alright.

Okay, ignore, fine.

**Pull request merged**
