### PR TITLE
chore: move react from devDependency to dependency in design system starter template

### PR DESCRIPTION
**Pull request by ghdtjgus76**
### Description

I mentioned this in discussions, in the design system starter template, react was specified as a devDependency rather than a dependency. 
It needs to be moved to dependencies.

https://github.com/vercel/turbo/discussions/8156

### Testing Instructions

### CODE REVIEW

**Review by mehulkar — COMMENTED** [review]
I _think_ this is correct, but @anthonyshew is the right person to ask. I'd almost want `react` to be a peerDep in a shared package, not a real dep.

**Review by anthonyshew — APPROVED** [review]
Thanks! Appreciate the attention to detail. 🙌

**Review by anthonyshew — CHANGES_REQUESTED** [review]
Can you update the lockfile to reflect this change? Can merge after that!

**Comment by ghdtjgus76** [comment]
I reflected the changes!
Thank you for the comment. 😀

**Pull request merged**
