### PR TITLE
Fixes `new URL()` during SSR 

### PR DESCRIPTION
**Pull request by jridgewell**
A follow up to #2944, which incorrectly rewrote the `new URL("…", import.meta.url)` to `new URL("…", location.origin)` during server rendering (which obviously doesn't have a `location` object).

This PR accomplishes 2 things:
- Splits dev server address binding from setting up the handler function
  - This is necessary so that we can determine the bound server address during devs retry attempts.
- Propagates the server address through the `ExecutionEnvironment` to the `UrlAssetReference`

I chose to pipe the server address through the `ExecutionEnvironment` instead of the `EnvironmentIntention`, because I don't fully understand the differences between them. It seems like we want it in the intention for the types of rendering, but a server address is really tied to the node process, so I don't know.

Fixes WEB-318

### CODE REVIEW

**Review by sokra — CHANGES_REQUESTED** [review]
TBH it sounds like a really bad idea to embed the server url into the bundle. That can break in so many ways and we can't use that for production builds. Let's discuss that again...

**Comment by jridgewell** [comment]
Can we merge this to unbreak builds while we figure out a better approach?

- - -
 
> TBH it sounds like a really bad idea to embed the server url into the bundle

How else could we server render the asset? We need to create a `URL` instance, that has to be constructed with an absolute path, and the only way we can have an absolute path is to know what the server's URL is.

> we can't use that for production builds.

My expectation is that we'll take in a server URL and require it if you use the asset reference pattern anywhere.

**Comment by sokra** [comment]
> How else could we server render the asset? We need to create a `URL` instance, that has to be constructed with an absolute path, and the only way we can have an absolute path is to know what the server's URL is.

e. g. webpack (and next.js) uses a `FakeURL` instance which allows server-relative URLs too. It's also a kind of hack, but at least it avoids the server address in the generated code and it works for production builds too.

**Review by sokra — APPROVED** [review]
Temporarily accepting that

**Pull request merged**
