### PR TITLE
Add "scroll to top" option in theme.config.tsx

### PR DESCRIPTION
**Pull request by mitesh-gupta**
It will give an option to users to go back to top of the page

image

### CODE REVIEW

**Review by mehulkar — CHANGES_REQUESTED** [review]
Thanks for the contribution! I'm not seeing this link, where is your screenshot from? I pulled this branch down locally and don't see it in the right sidebar of the turborepo or turbopack docs pages. I do see this option in the Nextra docs though, so I must be missing something: https://nextra.site/docs/docs-theme/theme-configuration#table-of-contents

**Comment by tknickman** [comment]
This was added to nextra in [2.12.0](https://github.com/shuding/nextra/releases/tag/nextra-theme-docs%402.12.0), and we're only on 2.1.0, so we'll need a nextra update for this.

**Comment by mitesh-gupta** [comment]
@mehulkar @tknickman Updated to latest version of nextra, now it should work as excepted.

**Comment by tknickman** [comment]
@mitesh-gupta I think we still need a lockfile update:
https://vercel.com/vercel/turbo-site/ENqaPtJa4fkQ3ohCCKqg6YRMLSnu#L19

A `pnpm install` should fix it up!

**Comment by mitesh-gupta** [comment]
@tknickman Done.

**Review by tknickman — APPROVED** [review]
lgtm - thanks!

**Review by mehulkar — APPROVED** [review]

**Pull request merged**
