### PR TITLE
Rsc lib example

### PR DESCRIPTION
**Pull request by mayank1513**
### Added an example for creating libraries that unleash the full potential of React18 - especially the server components.

This example contain:
- Build setup that builds my-lib - can support server and client components
- Turbo repo generators that generate component file, component test file, and index file exporting the component and also updates index.ts files in the path.
- Plugin also removes test files and data-testid attributes from the final build

### Testing Instructions
- Create a repo using this example
- Test whether build is working and all tests are passing

### CODE REVIEW

**Comment by mayank1513** [comment]
### **Introducing Example: Leveraging Turborepo for React 18 Libraries**

This pull request introduces a comprehensive example that demonstrates the utilization of Turborepo to craft React 18 libraries, aimed at unleashing the full potential of server components. Here's what's included in this showcase:

- **Build Setup:** The example encompasses a robust build setup tailored for React 18 libraries. This setup is designed to support both server and client components seamlessly.

- **Turborepo Implementation:** Leveraging Turborepo, the example showcases an efficient approach to managing and organizing multiple packages within a single repository. This enables smoother collaboration and streamlined development workflows.

- **Enhanced Development Workflow:** With Turborepo, developers can enjoy improved efficiency and maintainability by automating various tasks such as generating component files, test files, and index files. Additionally, a plugin has been integrated to optimize the build process further by removing redundant test files and `data-testid` attributes.

**Testing Instructions:**

To validate the efficacy of these changes, please follow these steps:

1. **Repository Creation:** Set up a repository using the provided example.
2. **Build and Test:** Ensure that the build process functions correctly and that all tests pass seamlessly.

Your feedback on these enhancements is invaluable. Thank you for reviewing!

**Comment by anthonyshew** [comment]
Thanks for the pull request!

The `basic` example already has an RSC library in it for folks to take a look at. Additionally, I spy some problems with what's proposed here:
- We don't want to encourage barrel files since they can quickly make for large compilation times.
- Today, the odds are high that you should use a bundler for a TypeScript library, opting for `tsc` instead.
- In general, there's a little too much configuration going on for a "starter". For example, the plugin to remove test IDs. We want the examples in the repo to be as absolutely minimal as possible.

I definitely appreciate your willingness to contribute! However, we'll close this one as we're not looking to have more examples in the repo, in general.

**Comment by mayank1513** [comment]
Thanks for the quick response. This example was targeted for library creators who wish to craft and publish their libraries with full power of React 18.

- There is just one plugin used. Removing test files etc. are just byproduct. The main focus is creating a build which adds “use client” directive to selected components only.
- I don't see any example in this directory that demonstrates how to build RSC compatible libraries
- Barrel files can be removed if you wish to accept and move ahead with the basic/bare minimum build set up for building RSC compatible libraries. 

Should I update the example and reopen this PR or create a new one?

Looking forward to your positive response.

**Comment by mayank1513** [comment]
Also, there is no example showing how to use CSS/CSS modules inside the library. 

- No use creating UI component as a shared library component but keeping the multiple copies of style sheets in each app

I have a solution for this as well. And if you and your team agree to add such an example, I shall create that one as well. Your reply is highly appreciated.

**Comment by mayank1513** [comment]
A popular openion: 

- In practice, the benefits of using barrel files in terms of code organization and maintainability often outweigh any minor increase in compilation time. Additionally, **modern build tools and compilers are generally optimized to handle large codebases efficiently**, so the impact on compilation time should be manageable.

**Pull request closed without merging**
