### PR TITLE
chore: install jest in examples/kitchen-sink

### PR DESCRIPTION
**Pull request by llllvvuu**
Otherwise `pnpm test` doesn't work.

### CODE REVIEW

**Review by tknickman — APPROVED** [review]
Generally, we should only put this in each package where it is used (`package/ui`, `apps/api`) to properly segment the cache when this needs to be updated. However, I'm also fine with root for this specific case (devDependencies that generally need to be the same version across the entire repo).

**Comment by anthonyshew** [comment]
@llllvvuu Can you install `jest` in the packages where it is used? We're going to more generally start recommending this pattern to folks and this can be an early move in that direction. Thanks!

**Comment by llllvvuu** [comment]
Sure, done!

**Review by anthonyshew — APPROVED** [review]
Awesome, thank you!

**Comment by anthonyshew** [comment]
Merging through the failed formatter CI check because it comes from a GitHub permission being weird. I've confirmed that these changes have nothing to do with the formatter.

**Pull request merged**
