### PR TITLE
Allow fallback to be used outside VERCEL

### PR DESCRIPTION
**Pull request by cipriancaba**
### Description

When not on vercel, there is no way to use fallback against a specific sha with turbo-ignore
This solves #1641

### Testing Instructions

Do a `turbo-ignore` with a provided `fallback` outside vercel

### CODE REVIEW

**Review by arlyon — APPROVED** [review]
This feature seems reasonable to me. Thanks for using turbo :)

**Comment by cipriancaba** [comment]
Thanks @arlyon . I think it should be fine now?

**Comment by gsoltis** [comment]
@cipriancaba Thanks for your contribution, this definitely looks like a good idea.

Some tests are still failing: `Turbo error: failed to resolve packages to run: git error: fatal: Invalid symmetric difference expression 32b6e5b3b8e0f460828a691f2fdff89fe82f005a...HEAD` [here](https://github.com/vercel/turbo/actions/runs/5667787256/job/15367083735?pr=5614#step:5:16)

I'm assuming that's related to the change. Once that's fixed up, let's get it merged! Give a shout if you need help debugging.

**Comment by cipriancaba** [comment]
That was a really weird error @gsoltis . Hopefully my branch update did the trick? 

I think I am still waiting for an approval to retrigger the worfklow?

**Comment by gsoltis** [comment]
Kicked it off

**Comment by cipriancaba** [comment]
Thanks @gsoltis . It seems to be happy now, just some Authorization still needed

**Pull request merged**
