### PR TITLE
chore(packages/ui turbo gen config.ts): Preventing the format of pack…

### PR DESCRIPTION
**Pull request by moeyashi**
…age.json from being corrupted

### Description

Prevent the format of `package.json` from getting corrupted when creating a component with `turbo gen`.

Here's what the exports section looks like before and after the fix:

before

```
  "exports": {
"./foo": "./src/foo.tsx",
    "./button": "./src/button.tsx",
    "./card": "./src/card.tsx",
    "./code": "./src/code.tsx"
  },
```

after

```
  "exports": {
    "./foo": "./src/foo.tsx",
    "./button": "./src/button.tsx",
    "./card": "./src/card.tsx",
    "./code": "./src/code.tsx"
  },
```

### Testing Instructions

1. Create a component with `turbo gen`.
2. Check package.json.

### CODE REVIEW

**Comment by anthonyshew** [comment]
Hi, thanks for the contribution!

Can you explain a little more about the nature of the "corruption" this PR is meant to solve?

**Comment by moeyashi** [comment]
Thank you for your review.

I edited this issue to explain what this PR is trying to solve.

"corrupted" may not be a good expression. "broken", "incorrect" and "wrong" are candidates.

**Comment by anthonyshew** [comment]
Just so I'm clear on what I'm seeing here: There's a missing tab character when the generator is run?

**Comment by moeyashi** [comment]
Yes, there's a missing tab character.

But my fix is ​​to indent with 4 spaces instead of a tab character.

**Review by anthonyshew — APPROVED** [review]
Sounds good! Thanks!

**Pull request merged**
