### PR TITLE
add tags to turbo tasks

### PR DESCRIPTION
**Pull request by arlyon**
### Testing Instructions

Closes TURBO-2878

### CODE REVIEW

**Comment by arlyon** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/vercel/turbo/8038?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#8038** <a href="https://app.graphite.dev/github/pr/vercel/turbo/8038?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#8037** <a href="https://app.graphite.dev/github/pr/vercel/turbo/8037?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#7675** <a href="https://app.graphite.dev/github/pr/vercel/turbo/7675?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#7674** <a href="https://app.graphite.dev/github/pr/vercel/turbo/7674?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#7673** <a href="https://app.graphite.dev/github/pr/vercel/turbo/7673?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arlyon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by chris-olszewski** [comment]
@arlyon Did you mean to tag Nick and I as reviewers for this PR?

**Comment by arlyon** [comment]
No, oops. I tagged you on the other one but I swear I didn't do it twice ... Sorry 😂

**Review by bgw — APPROVED** [review]

**Comment by arlyon** [comment]
### Merge activity

* **Jul 24, 3:11 PM EDT**: @arlyon merged this pull request with [Graphite](https://app.graphite.dev/github/pr/vercel/turbo/8038).

**Pull request merged**
